<?php

/**
* @name        JMY CMS
* @link        http://jmy.su/
* @copyright   Copyright (C) 2012-2014 JMY LTD
* @license     LICENSE.txt (see attached file)
* @version     VERSION.txt (see attached file)
* @author      Komarov Ivan
* @edit 	   03.02.2015
*/

define('_GLOBAL', 'Основные конфигурации');
define('_GLOBAL_METATAGS', 'Настройка мета-тегов');
define('_GLOBAL_METATAGS_URLT', 'URL сайта');
define('_GLOBAL_METATAGS_URLD', 'Главная настройка системы адрес с http:// без / в конце');
define('_GLOBAL_METATAGS_NAMET', 'Имя сайта');
define('_GLOBAL_METATAGS_NAMED', 'Будет постоянно отображаться в meta-теге &lt;title&gt;&lt;/title&gt;');
define('_GLOBAL_METATAGS_DESCRIPTIONT', 'Описание сайта');
define('_GLOBAL_METATAGS_DESCRIPTIOND', 'Будет отображаться в meta-теге description');
define('_GLOBAL_METATAGS_SLOGANT', 'Слоган сайта');
define('_GLOBAL_METATAGS_SLOGAND', 'Будет отображаться в meta-теге &lt;title&gt;&lt;/title&gt; рядом с "Название сайта"');
define('_GLOBAL_METATAGS_KEYWORDST', 'Ключевые слова');
define('_GLOBAL_METATAGS_KEYWORDSD', 'Подумайте перед тем, как заполнить поле. Оно служит для оптимизации сайта для поисковых систем!');
define('_GLOBAL_METATAGS_DIVIDERT', 'Сепаратор');
define('_GLOBAL_METATAGS_DIVIDERD', 'Сепаратор служит для разделения заголовков в &lt;title&gt;&lt;/title&gt; вводить с пробелами [пробел|пробел]');
define('_GLOBAL_METATAGS_CHARSETT', 'Кодировка сайта');
define('_GLOBAL_METATAGS_CHARSETD', 'Если Вы не знаете, что это за поле, не меняйте');
define('_GLOBAL_METATAGS_MAINMODULET', 'Модуль на главной');
define('_GLOBAL_METATAGS_MAINMODULED', 'Имя папки модуля, который должен отображаться на главной');
define('_GLOBAL_METATAGS_LANGT', 'Язык сайта');
define('_GLOBAL_METATAGS_LANGD', 'Выберите язык сайта');
define('_GLOBAL_METATAGS_MULTILANGT', 'Мультиязычность');
define('_GLOBAL_METATAGS_MULTILANGD', 'Будет ли ваш сайт поддерживать несколько языков?');
define('_GLOBAL_OTHER', 'Прочее');
define('_GLOBAL_OTHER_ENGINEVERSIONT', 'Версия системы');
define('_GLOBAL_OTHER_ENGINEVERSIOND', 'Версия системы');
define('_GLOBAL_OTHER_UNIQKEY', 'Уникальный код сайта');
define('_GLOBAL_OTHER_UNIQKEYD', 'Данный код защищает ваш сайт от взлома, каждый сайт имеет свой уникальный код, поэтому угадать его невозможно.');
define('_GLOBAL_OTHER_ENGINECREATORST', 'Разработчики системы');
define('_GLOBAL_OTHER_ENGINECREATORSD', 'Знай в лицо :)');
define('_GLOBAL_OTHER_TIMEZONET', 'Временной пояс');
define('_GLOBAL_OTHER_TIMEZONED', 'Выберите GMT пояс для вашего сайта. Все даты на сайте будут отформатированы по его настройкам.');
define('_GLOBAL_OTHER_TPLT', 'Тема оформления');
define('_GLOBAL_OTHER_TPLD', 'Выберите из списка предложенные темы оформления для вашего сайта');
define('_GLOBAL_OTHER_TPL_MOBI', 'Включить шаблон для смартфонов');
define('_GLOBAL_OTHER_TPL_MOBI_DESC', 'Если пользователь будет заходить с мобильного устройства, то шаблон будет загружаться из папки usr/tpl/smartphone');
define('_GLOBAL_OTHER_TPL_CHANGE', 'Разрешить смену шаблона на сайте');
define('_GLOBAL_OTHER_TPL_CHANGE_DESC', 'Если Вы используете несколько шаблонов на сайте, то вы можете разрешить посетителям переключаться между ними');
define('_GLOBAL_OTHER_DBTYPET', 'Тип базы данных');
define('_GLOBAL_OTHER_DBTYPED', 'Выберите из списка тип базы данных который используется у вас на сервере');
define('_GLOBAL_OTHER_IMAGEEFFECTT', 'Эффект картинок');
define('_GLOBAL_OTHER_IMAGEEFFECTD', 'Выберите из списка эффект, который будет использоваться при раскрытии картинок.');
define('_GLOBAL_OTHER_SUPPORT_MAILT', 'E-Mail для связи');
define('_GLOBAL_OTHER_SUPPORT_MAILD', 'Данный электронный адрес будет использоваться в функциях обратной связи');
define('_GLOBAL_GLOBALFUNC', 'Глобальные функции системы');
define('_GLOBAL_GLOBALFUNC_GZIPT', 'Активировать сжатие G-Zip?');
define('_GLOBAL_GLOBALFUNC_GZIPD', 'Сжатие позволит экономить трафик ваших пользователей, но не злоупотребляйте данной функцией на крупных порталах.');
define('_GLOBAL_GLOBALFUNC_OFFT', 'Закрыть сайт на профилактику');
define('_GLOBAL_GLOBALFUNC_OFFD', 'Если ваш сайт ещё не доделан закройте его на профилактику и продолжайте работу');
define('_GLOBAL_GLOBALFUNC_OFF_TEXTT', 'Текст при профилактике');
define('_GLOBAL_GLOBALFUNC_OFF_TEXTD', 'Текст который будет отображаться при профилактическом режиме');
define('_GLOBAL_GLOBALFUNC_FULLAJAXT', 'Активировать FullAjax?');
define('_GLOBAL_GLOBALFUNC_FULLAJAXD', 'BETA РЕЖИМ.');
define('_GLOBAL_GLOBALFUNC_REFFERT', 'Учитывать рефферов?');
define('_GLOBAL_GLOBALFUNC_REFFERD', 'При включении система будет вести логи заходов на сайт с поисковых систем.');
define('_GLOBAL_GLOBALFUNC_CACHET', 'Активировать кэширование?');
define('_GLOBAL_GLOBALFUNC_CACHED', 'Если у вас большой портал Вы можете активировать кэшированние отдельных частей сайта');
define('_GLOBAL_GLOBALFUNC_DBCACHET', 'Активировать кэширование базы данных?');
define('_GLOBAL_GLOBALFUNC_DBCACHED', 'Если у вас большой портал, то Вы можете активировать кэшированние базы данных.');
define('_GLOBAL_GLOBALFUNC_COMMENTST', 'Активировать систему комментариев');
define('_GLOBAL_GLOBALFUNC_COMMENTSD', 'Если Вы не используете комментарии на сайте, отключите их.');
define('_GLOBAL_GLOBALFUNC_MOD_REWRITET', 'Активировать ЧПУ');
define('_GLOBAL_GLOBALFUNC_MOD_REWRITED', 'Отключение человеко-понятных url приведёт к повышению нагрузки на сайте');
define('_GLOBAL_GLOBALFUNC_COUNTERT', 'Подсчитывать посетителей?');
define('_GLOBAL_GLOBALFUNC_COUNTERD', 'В системе есть встроенная функция подсчёта посещений. Вы можете вывести её с помощью блока.');
define('_GLOBAL_GLOBALFUNC_PLUGINT', 'Включить класс интеграции?');
define('_GLOBAL_GLOBALFUNC_PLUGIND', 'Если включить эту опцию, то в профиле будет подключён класс plugin, который можно переписать как интеграцию к стандартным функциям.');
define('_SECURITY', 'Настройки безопасности системы');
define('_SECURITY_INFORMATION', 'К полям <i>Запрещённые ники, Запрещённые e-mail, Стоп-слова, Заблокированные IP</i> можно применить следующее правило:<br />* - <u>любые символы, будь то цифры, буквы или знаки</u> <br />% - <u>только 1 любой символ!</u><br /><b>Пример:</b><br/>%laed* - заблокирует slaed, laed, slaed_cms и тп.');
define('_SECURITY_FILTER', 'Фильтрация данных');
define('_SECURITY_FILTER_XNUMST', 'Секретный код');
define('_SECURITY_FILTER_XNUMSD', 'Введите код состоящий максимум из 6 символов! Он будет использован для шифровки данных.');
define('_SECURITY_FILTER_STOPNICKT', 'Запрещённые ники');
define('_SECURITY_FILTER_STOPNICKD', 'Данная опция позволит Вам запретить регистрацию под определёнными никами. <br/>Вводить их следует через запятую(,).');
define('_SECURITY_FILTER_STOPMAILST', 'Запрещенные e-mail');
define('_SECURITY_FILTER_STOPMAILSD', 'Опция не позволит использовать e-mail из списка при регистрации, оставлении комментариев а также использовать для формы обратный связи. Формат ввода через запятую(,).');
define('_SECURITY_FILTER_STOPWORDST', 'Стоп-слова');
define('_SECURITY_FILTER_STOPWORDSD', 'Стоп-слова служат для упреждения цензурных выражений в публикациях сайта.');
define('_SECURITY_FILTER_STOPREPLACET', 'Замена стоп-слов');
define('_SECURITY_FILTER_STOPREPLACED', 'Все стоп-слова из списка будут заменены на данное значение.<br /> Оставьте пустым и слова просто будут вырезаться.');
define('_SECURITY_FILTER_ALLOWHTMLT', 'Разрешённые HTML теги');
define('_SECURITY_FILTER_ALLOWHTMLD', 'Перечислите через запятую теги, которые могут быть использованы на сайте.');
define('_SECURITY_IPS', 'Блокировка по IP');
define('_SECURITY_IPS_BANIPT', 'Заблокированные IP');
define('_SECURITY_IPS_BANIPD', 'Если при заходе на сайт обнаружится, что IP пользователя находится в данном списке, то доступ к сайту ему, будет ограничен.');
define('_SECURITY_IPS_BANIPMESSAGET', 'Сообщение при блокировке');
define('_SECURITY_IPS_BANIPMESSAGED', 'Сообщение которое будет отображено при конфликте IP.');
define('_SECURITY_SWITCH', 'Включить капчу?');
define('_SECURITY_SWITCH_DESC', 'Активировать проверку спам-ботов?');
define('_SECURITY_CAPTCHA', 'Настройка Каптчи(Captcha)');
define('_SECURITY_RECAPTHA', 'Использовать ReCaptcha?');
define('_SECURITY_RECAPTHA_DESC', 'Использовать ReCaptcha?');
define('_SECURITY_RECAPTHA_PUBLIC', 'Публичный ключ ReCaptcha');
define('_SECURITY_RECAPTHA_PUBLIC_DESC', 'Получить публичный ключ вы можете по ссылке: http://www.google.com/recaptcha');
define('_SECURITY_RECAPTHA_PRIVATE', 'Приватный ключ ReCaptcha');
define('_SECURITY_RECAPTHA_PRIVATE_DESC', 'Получить приватный ключ вы можете по ссылке: http://www.google.com/recaptcha');
define('_SECURITY_CAPTCHA_CAPTCHA_WIDTHT', 'Ширина каптчи');
define('_SECURITY_CAPTCHA_CAPTCHA_WIDTHD', 'Ширина в пикселях');
define('_SECURITY_CAPTCHA_CAPTCHA_HEIGHTT', 'Высота каптчи');
define('_SECURITY_CAPTCHA_CAPTCHA_HEIGHTD', 'Высота в пикселях');
define('_SECURITY_CAPTCHA_CAPTCHA_LENGHTT', 'Кол-во знаков');
define('_SECURITY_CAPTCHA_CAPTCHA_LENGHTD', 'При выставлении количества знаков, будте внимательны, не забывайте, что от количества знаков зависит ширина и высота изображения!');
define('_FILES', 'Управление файлами');
define('_FILES_FILE', 'Общие параметры');
define('_FILES_FILE_IMGFORMATST', 'Форматы изображение');
define('_FILES_FILE_IMGFORMATSD', 'Перечислите через запятую те форматы которые в системе должны индифицироваться как изображения');
define('_FILES_FILE_ATTACHFORMATST', 'Форматы аттачей');
define('_FILES_FILE_ATTACHFORMATSD', 'Форматы файлов которые в системе будут загружаться как аттачи(файлы) и будут доступны для скачивания в виде ссылки.');
define('_FILES_FILE_MAX_SIZET', 'Максимальный размер');
define('_FILES_FILE_MAX_SIZED', 'Максимальный размер загружаемых файлов в байтах');
define('_FILES_THUMB', 'Создание превью(тумбочек)');
define('_FILES_THUMB_THUMB_WIDTHT', 'Ширина превью');
define('_FILES_THUMB_THUMB_WIDTHD', 'Максимальная ширина изображения, при превышении, картинка будет автоматически уменьшена. Ширина в px');
define('_FILES_THUMB_QUALITYT', 'Качество превью');
define('_FILES_THUMB_QUALITYD', 'Число указывается в %. Чем меньше цифра тем меньше будут весить превью.');
define('_FILES_WATERMARK', 'Водяной знак(WaterMark)');
define('_FILES_WATERMARK_WATERMARKT', 'Включить watermark?');
define('_FILES_WATERMARK_WATERMARKD', 'При включённой опции на все картинки загружаемые через сервисы сайта будет наложен водяной знак.');
define('_FILES_WATERMARK_WATERMARK_TEXTT', 'Текст водяного знака');
define('_FILES_WATERMARK_WATERMARK_TEXTD', 'Если не указана картинка ватермарка будет наложен указанный текст. Рекомендуется только с GD2');
define('_FILES_WATERMARK_WATERMARK_IMAGET', 'Картинка водяного знака');
define('_FILES_WATERMARK_WATERMARK_IMAGED', 'Чтобы наложить картинку на изображение, укажите её адрес тут. Ватермарк должен быть в формате PNG и желательно с 24 битовым альфа каналом.');
define('_FILES_WATERMARK_WATERMARK_VALIGNT', 'Расположение по вертикале');
define('_FILES_WATERMARK_WATERMARK_VALIGND', 'Выберите расположение ватермарка в вертикальной плоскости.');
define('_FILES_WATERMARK_WATERMARK_HALIGNT', 'Расположение по горизонтали');
define('_FILES_WATERMARK_WATERMARK_HALIGND', 'Выберите расположение ватермарка в горизонтальной плоскости.');
define('_ADMIN', 'Настройка административной панели');
define('_ADMIN_MAIN', 'Общие параметры');
define('_ADMIN_MAIN_NUMT', 'Кол-во на страницу');
define('_ADMIN_MAIN_NUMD', 'Какое кол-во контента отображать на страницу в разделах админ панели.');
define('_ADMIN_MAIN_IPACCESST', 'Доступ по IP');
define('_ADMIN_MAIN_IPACCESSD', 'Ограничение доступа в административную панель по IP. Если пустое - доступ всем.');
define('_ADMIN_MAIN_IPACCESS_HELP', '<br />Пример (начало диапазона|конец диапазона): <br /><i>192.168.0.0|192.168.255.255<br />83.15.0.0|84.20.255.255</i><br />Каждая группа диапазонов с новой строки.');
define('_ADMIN_HTMLEDITORT', 'Использовать HTML редактор');
define('_ADMIN_HTMLEDITORD', 'Использовать HTML редактор при добавлении постов в административной панели');
define('_ADMIN_MAIN_SESSIONST', 'Активировать сессии');
define('_ADMIN_MAIN_SESSIONSD', 'Если данный параметр включён, вход в панель управления будет производиться каждый раз отдельно при перезагрузке браузера.');
define('_ADMIN_MAIN_BART', 'Информационный бар');
define('_ADMIN_MAIN_BARD', 'Активировать информационный бар, для быстрой навигации на страницах сайта?');
define('_USERC', 'Настройка пользовательской части');
define('_USER_MAIN', 'Группы');
define('_USER_MAIN_GUESTGROUPT', 'Группа гостей');
define('_USER_MAIN_GUESTGROUPD', 'Выберите группу, к которой будут относится гости');
define('_USER_MAIN_BOTGROUPT', 'Группа ботов');
define('_USER_MAIN_BOTGROUPD', 'Выберите группу, к которой будут относится поисковые боты');
define('_USER_MAIN_BANGROUPT', 'Группа забаненых');
define('_USER_MAIN_BANGROUPD', 'Выберите группу, к которой будут относится забаненые пользователи');
define('_USER_COUNT_POINTST', 'Подсчёт очков');
define('_USER_COUNT_POINTSD', 'Вести подсчёт "очков" пользователей, при выполнении определённых действий на сайте?');
define('_USER_AVATAR', 'Настройка аватара');
define('_USER_AVATAR_NOAVATART', 'Картинка "Нет аватара"');
define('_USER_AVATAR_NOAVATARD', 'Укажите адрес картинки, которая будет у пользователя без аватара.');
define('_USER_AVATAR_AVATAR_LOADT', 'Загружать аватары');
define('_USER_AVATAR_AVATAR_LOADD', 'Опция загрузки аваторов на сервер');
define('_USER_AVATAR_AVATAR_WIDTHT', 'Ширина аватара');
define('_USER_AVATAR_AVATAR_WIDTHD', 'Максимальная ширина аватара в px');
define('_USER_AVATAR_AVATAR_HEIGHTT', 'Высота аватара');
define('_USER_AVATAR_AVATAR_HEIGHTD', 'Максимальная высота аватара в px');
define('_USER_AVATAR_AVATAR_SIZET', 'Максимальный размер аватара');
define('_USER_AVATAR_AVATAR_SIZED', 'Максимальная размер аватара в б');
define('_USER_REGISTER', 'Регистрация');
define('_USER_REGISTER_WITH_ACTIVATET', 'Регистрация с активацией?');
define('_USER_REGISTER_WITH_ACTIVATED', 'После регистрации посылать на почту пользователя письмо с подтверждением?');
define('_USER_BBEDITOR', 'Редакторы');
define('_USER_BBEDITOR_ACTIVEFLASHT', 'Разрешить добавление flash');
define('_USER_BBEDITOR_ACTIVEFLASHD', 'Разрешаете ли Вы использовать тэг [flash][/flash] в пользовательском бб-редакторе?');
define('_USER_BBEDITOR_ACTIVEVIDEOT', 'Разрешить видео ссылок');
define('_USER_BBEDITOR_ACTIVEVIDEOD', 'Разрешаете ли Вы использовать тэг [video][/video] в пользовательском бб-редакторе?');
define('_USER_BBEDITOR_ACTIVEAUDIOT', 'Разрешить аудио ссылок');
define('_USER_BBEDITOR_ACTIVEAUDIOD', 'Разрешаете ли Вы использовать тэг [audio][/audio] в пользовательском бб-редакторе?');
define('_USER_BBEDITOR_ACTIVEATTACHT', 'Разрешить добавление файлов');
define('_USER_BBEDITOR_ACTIVEATTACHD', 'Разрешаете ли Вы использовать загрузку файлов пользователями сайта?');
define('_USER_BBEDITOR_HIGHLGIHTT', 'Подсвечивать синтаксис кода?');
define('_USER_BBEDITOR_HIGHLGIHTD', 'Использовать подсветку синтаксиса для тега [code=...][/code]?');
define('_USER_BBEDITOR_EDITORT', 'Какой редактор использовать');
define('_USER_BBEDITOR_EDITORD', 'Выберите какой редактор будет доступен пользователям для работы');
define('_USER_BBEDITOR_BBVIZT', 'Визуализация BB редактора');
define('_USER_BBEDITOR_BBVIZD', 'Опция предоставляет возможность пользователям сразу видеть результат парсинга текста в редакторе');
define('_USER_COMMENTS', 'Комментарии');
define('_USER_COMMENTS_COMMENTOFTENT', 'Время между комментариями');
define('_USER_COMMENTS_COMMENTOFTEND', 'Установите промежуток времени в секундах через который будет доступно добавлять комментарии. Чтобы отключить данную опцию установите 0.');
define('_USER_COMMENTS_COMMTREET', 'Древовитые комментарии');
define('_USER_COMMENTS_COMMTREED', 'Функция позволит пользователям отвечать на комментарии, создавая подобие древа.');
define('_USER_COMMENTS_COMMEDTEXT', 'Пометка для редактированных комментариев');
define('_USER_COMMENTS_COMMEDTEXTD', '{user} - имя пользователя, {date} - дата редактирования. Оставьте пустым, если хотите отключить данную функцию.');
define('_USER_COMMENTS_COMMMODERATE', 'Премодерация комментариев');
define('_USER_COMMENTS_COMMMODERATED', 'Если включить данную функцию, то Вы будете обязаны модерировать каждый комментарий, который будет добавлен Вам на сайт.');
define('_USER_COMMENTS_SUBSCRIBET', 'Подписка на комментарии');
define('_USER_COMMENTS_SUBSCRIBED', 'Позволить пользователям подписаться на комментарии, которые им будут высылаться на e-mail адрес.');
define('_USER_COMMENTS_SIGNATURET', 'Шаблон подписи');
define('_USER_COMMENTS_SIGNATURED', 'Отредактируйте шаблон подписи пользователя для комментариев системы. Если данное поле будет пустым, подпись выводиться не будет!');
define('_USER_OTHER', 'Разное');
define('_USER_OTHER_PMSHOWNT', 'Сообщения о новых PM');
define('_USER_OTHER_PMSHOWND', 'Показывать сообщения при получении новых PM пользователю. +1 запрос к базе данных');
define('_USER_OTHER_ISBANT', 'Разрешить бан пользователей?');
define('_USER_OTHER_ISBAND', 'Если Вы считаете, что никогда не будете применять бан, отключите данную функцию');
define('_USER_OTHER_USERWALLT', 'Активировать стену пользователя?');
define('_USER_OTHER_USERWALLD', 'Стена позволяет пользователям оставлять сообщение и мнения в профилях сайта.');
define('_USER_OTHER_USERWALLNUMT', 'Записей стены на одну страницу');
define('_USER_OTHER_USERWALLNUMD', 'Сколько записей пользователя отображать на одной странице');
define('_USER_OTHER_USERFRIENDST', 'Дружба между пользователей');
define('_USER_OTHER_USERFRIENDSD', 'Расширяет возможности взаимодействия пользователей между собой');
define('_USER_OTHER_USERGUESTST', 'Учитывать гостей пользователя');
define('_USER_OTHER_USERGUESTSD', 'Система будет записывать и выводить пользователей которые посещали страницу');
define('_USER_OTHER_READBLOGT', 'Подпись на блоги');
define('_USER_OTHER_READBLOGD', 'Выводить блоги, на которые подписан пользователь?');
define('_FULLAJAX', 'Настройка системы FullAjax');
define('_FULLAJAX_MAIN', 'Основные настройки');
define('_FULLAJAX_MAIN_LOADERT', 'ID загрузчика');
define('_FULLAJAX_MAIN_LOADERD', 'Укажите ID слоя загрузчика, который будет показываться/скрываться при работе FullAjax.<br />Стандартный загрузчик системы: loading');
define('_FULLAJAX_MAIN_LOADERSTATICT', 'Загрузчик статичный?');
define('_FULLAJAX_MAIN_LOADERSTATICD', 'Если загрузчик не двигается за страницей пользователя а находится в установленном месте, то следует отметить ДА.<br />По стандарту загрузчик не статичен!');
define('_FULLAJAX_MAIN_REPLACET', 'Замена в ссылках');
define('_FULLAJAX_MAIN_REPLACED', 'http://site.ru/#{тут замена}/board. Замена должна быть обязательно уникальна!');
define('_FULLAJAX_MAIN_BLOCKLINKST', 'Блокировать Ajax в ссылках');
define('_FULLAJAX_MAIN_BLOCKLINKSD', 'Укажите через запятую ссылки которые FullAjax будет игнорировать.<br/>Например: feedback,content,board,board/forum-');
define('_FULLAJAX_MAIN_STORAGET', 'Система Storage');
define('_FULLAJAX_MAIN_STORAGED', 'Читайте здесь: <a href="http://habrahabr.ru/blogs/AJAX/26784/">http://habrahabr.ru/blogs/AJAX/26784/</a>');
define('_FULLAJAX_MAIN_FREECODET', 'Свой код');
define('_FULLAJAX_MAIN_FREECODED', 'Добавьте свой код к системе');
define('_LOG', 'Настройка логирования');
define('_LOG_MAIN', 'Логирование ошибок'); 
define('_LOG_MAIN_PHPERRORT', 'Ошибки php');
define('_LOG_MAIN_PHPERRORD', 'Если при выполнении скрипта возникли ошибки, то они будут занесены в логи');
define('_LOG_MAIN_QUERYERRORT', 'Ошибки фильтрации');
define('_LOG_MAIN_QUERYERRORD', 'При попытке взлома или при обнаружении опасности система запишет в лог информацию и остановит злоумышленников');
define('_LOG_MAIN_DBERRORT', 'Ошибки базы данных');
define('_LOG_MAIN_DBERRORD', 'Логирования ошибок базы данных');
define('_LOG_MAIN_ACCESERRORT', 'Ошибки доступа и сайта');
define('_LOG_MAIN_ACCESERRORD', 'В лог будут записаны ошибки 403,404, а также неудачные входы в панель управления');
define('_LOG_MAIN_COMPRESSSIZET', 'Предельный размер файла');
define('_LOG_MAIN_COMPRESSSIZED', 'Указывается в байтах. После достижения этого размера, лог будет упакован в gz архив и спрятан на сервере.');

define('_CACHE_CONFIG', 'Настройки кэширования');
define('_CACHE_TPL', 'Структура файлов TPL');
define('_CACHE_TPL_DESC', 'Кэшировать структуру и наличие tpl файлов');
define('_CACHE_BLOCK', 'Блоки и модули');
define('_CACHE_BLOCK_DESC', 'Позволяет не производить запрос при каждом обновлении страницы');
define('_CACHE_CAT', 'Категории');
define('_CACHE_CAT_DESC', 'Кэширует полный список категорий, сокращает потребность в отдельном запросе');
define('_CACHE_USER', 'Данные пользователя');
define('_CACHE_USER_DESC', 'Хранит актуальную информацию о пользователе');

define('_CONFIG_MODULES', 'Настройка модулей:');

define('_BACKUP_NAME', 'Резервные копии');
define('_BACKUP_ADD', 'Создание резервной копии');
define('_BACKUP_ERROR_0', 'Вы не выбрали модули для резервного копирования! Вернитесь <a href="javascript:history.go(-1)" title="Назад">назад</a> и сделайте выбор.');
define('_BACKUP_ERROR_1', 'Вы добавили неверный файл конфигураций');
define('_BACKUP_MAKE_COPY', 'Создать копию');
define('_BACKUP_RESTORE_FILE', 'Восстановление из фала:');
define('_BACKUP_RESTORE_DESC', 'Восстановить из резервной копии');
define('_BACKUP_RESTORE_NAME', 'Восстановление резервной копии');
define('_BACKUP_RESTORE_LOG_1', 'Сохранение конфигураций в');
define('_BACKUP_RESTORE_LOG_2', 'успешно');

define('_SOCIAL_NAME', 'Настройка авторизации через социальные сети');
define('_SOCIAL_SW', 'Основное');
define('_SOCIAL_SWITCH', 'Авторизация через соц сети');
define('_SOCIAL_SWITCH_DESC', 'Разрешить авторизацию через социальные сети?');
define('_SOCIAL_PASS', 'Пароль при входе');
define('_SOCIAL_PASS_DESC', 'Запрашивать пароль при входе? (Рекомендуемая опция, повышает безопасность!)');
define('_SOCIAL_ADMIN', 'Авторизация администратора');
define('_SOCIAL_ADMIN_DESC', 'Разрешить авторизацию через социальные сети администратору сайта?');
define('_SOCIAL_IS', 'Разрешить авторизацию');
define('_SOCIAL_IS_DESC', 'Разрешить авторизацию через эту социальную сеть?');
define('_SOCIAL_ID', 'ID сайта');
define('_SOCIAL_ID_DESC', 'ID сайта который вы можете получить по следующему адресу');
define('_SOCIAL_SECRET', 'Секретный ключ');
define('_SOCIAL_SECRET_DESC', 'Секретный ключ который вы можете получить по следующему адресу');
define('_SOCIAL_PUBLIC', 'Публичный ключ');
define('_SOCIAL_PUBLIC_DESC', 'Публичный ключ который вы можете получить по следующему адресу');

define('_SOCIAL_CONFIG_VK', 'Настройки от Вконтакте');
define('_SOCIAL_CONFIG_VK_URL', 'https://vk.com/editapp?act=create');
define('_SOCIAL_CONFIG_OK', 'Настройки от Одноклассников');
define('_SOCIAL_CONFIG_OK_URL', 'http://ok.ru/devaccess');
define('_SOCIAL_CONFIG_FB', 'Настройки от Facebook');
define('_SOCIAL_CONFIG_FB_URL', 'https://developers.facebook.com/apps');
define('_SOCIAL_CONFIG_GG', 'Настройки от Google+');
define('_SOCIAL_CONFIG_GG_URL', 'https://code.google.com/apis/console/');
define('_SOCIAL_CONFIG_YA', 'Настройки от Яндекс');
define('_SOCIAL_CONFIG_YA_URL', 'https://oauth.yandex.ru/client/new');
define('_SOCIAL_CONFIG_MM', 'Настройки от Mail.ru');
define('_SOCIAL_CONFIG_MM_URL', 'http://api.mail.ru/sites/my/add');