<?php

/**
* @name        JMY CMS
* @link        http://jmy.su/
* @copyright   Copyright (C) 2012-2015 JMY LTD
* @license     LICENSE.txt (see attached file)
* @version     VERSION.txt (see attached file)
* @author      Komarov Ivan
* @revision	   07.03.2015
*/

define('_BASE_GUEST_NAME', 'Гость (Имя)');
define('_BASE_GUEST_MAIL', 'Гость (E-mail)');
define('_BASE_USER_NAME', 'Пользователь');
define('_BASE_NAME', 'Имя');
define('_BASE_LIST', 'Список');
define('_BASE_CLEAR', 'Очистить');
define('_BASE_DELETE', 'Удалить');
define('_BASE_RESTORE', 'Восстановить');
define('_BASE_EMAIL', 'E-mail');
define('_BASE_SITE', 'Сайт');
define('_BASE_CONFIG', 'Настройки');
define('_BASE_GENDER', 'Пол');
define('_BASE_DATE', 'Дата');
define('_BASE_ACTIONS', 'Действие');
define('_BASE_FILE', 'Файл');
define('_BASE_GENDER_MALE', 'Мужской');
define('_BASE_GENDER_FEMALE', 'Женский');
define('_BASE_INFO_0', 'Действие успешно выполнено. <a href="javascript:history.go(-1)" >Вернуться.</a>');
define('_BASE_ERROR_0', 'Обязательные поля не были заполнены вернитесь <a href="javascript:history.go(-1)" title="Назад">назад</a> и исправьте ошибки!');
define('_BASE_ACTIVATE', 'Активировать');
define('_BASE_DACTIVATE', 'Активировать');
define('_BASE_EDIT', 'Редактировать');
define('_BASE_DELITE', 'Удалить');

define('_PANEL_MENU_MAIN', 'Главная');
define('_PANEL_MENU_NEWS', 'Материалы');
define('_PANEL_MENU_NEWS_MANAGER', 'Менеджер материалов');
define('_PANEL_MENU_NEWS_CAT', 'Менеджер категорий');
define('_PANEL_MENU_NEWS_XFIELDS', 'Дополнительные поля');
define('_PANEL_MENU_USER', 'Пользователи');
define('_PANEL_MENU_USER_MANAGER', 'Менеджер пользователей');
define('_PANEL_MENU_USER_GROUP', 'Группы');
define('_PANEL_MENU_USER_COMMENT', 'Комментарии');
define('_PANEL_MENU_USER_POLL', 'Опросы');
define('_PANEL_MENU_COM', 'Компоненты');
define('_PANEL_MENU_COM_FORUM', 'Форум');
define('_PANEL_MENU_COM_GALLERY', 'Галерея');
define('_PANEL_MENU_COM_GUESTBOOK', 'Гостевая книга');
define('_PANEL_MENU_COM_STATIC', 'Статические страницы');
define('_PANEL_MENU_CONFIG', 'Настройки');
define('_PANEL_MENU_EXP', 'Расширения');
define('_PANEL_MENU_EXP_MODULES', 'Модули');
define('_PANEL_MENU_EXP_BLOCKS', 'HTML (PHP) блоки');
define('_PANEL_MENU_EXP_LANG', 'Редактор языков');
define('_PANEL_MENU_EXP_TPL', 'Шаблоны');
define('_PANEL_MENU_OTHER', 'Прочие');
define('_PANEL_MENU_OTHER_MAP', 'Карта сайта');
define('_PANEL_MENU_OTHER_SMILES', 'Смайлы');
define('_PANEL_MENU_OTHER_BD', 'База данных');
define('_PANEL_MENU_OTHER_LOG', 'Логи ошибок');
define('_PANEL_SUNMENU_WELCOME', 'Добро пожаловать');
define('_PANEL_SUNMENU_IP', 'Ваш IP:');
define('_PANEL_SUNMENU_PROFILE', 'Настройки профиля');
define('_PANEL_SUNMENU_STATS', 'Статистика');
define('_PANEL_SUNMENU_VIEW', 'Просмотр сайта');
define('_PANEL_SUNMENU_HELP', 'Помощь');
define('_PANEL_SUNMENU_EXIT', 'Выход');
define('_PANEL_SUNMENU_NOTIF', 'Уведомления');

define('_THERE_IS', 'Есть');
define('_DATE_PUB', 'Дата публикации');
define('_ACTIVATE_RATING', 'Активировать рейтинг');
define('_ACTIVATE_COMMENTS', 'Активировать комментарии');
define('_TOP_SET', 'Закрепить в топе');
define('_PUBLIC_INDEX', 'Разместить на главной');
define('_TAB_MAIN', 'Основное');
define('_TAB_CONTENT', 'Контент');
define('_TAB_CONTROL', 'Управление');
define('_U_ADDNEWS', 'Добавить новость');
define('_U_ADDBLOCK', 'Добавить <br />блок');
define('_U_CONF', 'Основные настройки');
define('_U_ADDPAGE', 'Добавить страницу');
define('_U_ADDCAT', 'Добавить категорию');
define('_U_ADDVOT', 'Добавить опрос');
define('_U_TPL', 'Шаблоны сайта');
define('_U_USR', 'Пользователи системы');
define('_U_RSS', 'RSS Граббер');
define('_APANEL', 'Панель управления');
define('_YOURIP', 'Ваш IP:');
define('_SYSVER', 'Версия системы');
define('_DBSIZE', 'Размер базы данных');
define('_ALLUSERS', 'Всего пользователей');
define('_ALLNEWS', 'Всего новостей');
define('_TIC', 'ТИЦ сайта');
define('_PR', 'PR сайта');
define('_PUBLICATIONS', 'Поступления');

define('_INSTALLEX', 'Удалите файл install.php - он угрожает безопасности вашего сайта!');
define('_ONMODER', 'Внимание! Пользователи добавили свежие материалы!');
define('_UPDATE_JMY', 'Внимание! Вышла новая версия JMY CMS. Будьте на волне!');
define('_NO_VERSION', 'Внимание! Не найден файл с версией JMY CMS! Восстановите его!');
define('_NOT_NOTIF', 'Нет уведомлений');
define('_LASTLOG', 'Последние входы');
define('_FALSELOG', 'Неудачные входы');
define('_LOGSCLEANED', 'Логи очищены');
define('_TABLECLEANED', 'Таблица очищена');
define('_NONINF', 'Информация отсутствует');
define('_CACHE_CLEANED', 'кэш удалён');
define('_CHECKUPDATE', 'Проверить обновления');
define('_NO_UPDATE', 'В данный момент обновлений нет.');
define('_NO_NEWS', 'В данный момент новостей нет.');
define('_NO_TURNS', 'У вас не осталось попыток, попробуйте позже.');
define('_FALSE_TURN', 'Пароль введён не верно! У вас осталось {turns} попытка(и)');
define('_SYSTEM_STATISTIC', 'Статистика системы');
define('_AP_WELOCME', 'Добро пожаловать в панель управления');
define('_LOG_WRITE', 'Вход {nick} в панель управления.');
define('_EMPTY_LOGIN', 'Имя или пароль пусты!');
define('_SAVE', 'Сохранить');
define('_SITE', 'Сайт');
define('_GOOD_LOGIN', 'Вход [nick] в панель управления.');
define('_BAD_LOGIN', 'Неудчаный вход [nick] в панель управления. Вводимый пароль [pass]');
define('_BLOCKS_NOT_FOUND', 'Блоков не найдено');
define('_DELETE_COMMENT', 'Удалить комментарий?');

define('_UPLOAD', 'Загрузить');
define('_CHOOSE', 'Выбрать');
define('_CHOOSED', 'Выбрано');

define('_MAIN_MAIN', 'Панель управления');
define('_MAIN_CREATE', 'Создать');
define('_MAIN_CREATE_DESC', 'Добавить материал');
define('_MAIN_LIST', 'Список');
define('_MAIN_LIST_DESC', 'Редактировать новости');
define('_MAIN_STATIC', 'Страница');
define('_MAIN_STATIC_DESC', 'Список страниц');
define('_MAIN_CONF', 'Настройки');
define('_MAIN_CONF_DESC', 'Настройки системы');
define('_MAIN_USER', 'Пользователи');
define('_MAIN_COMM', 'Комментарии');
define('_MAIN_LAST_USER', 'Последние комментарии');
define('_MAIN_LAST_COMM', 'Последние пользователи');
define('_MAIN_EMPTY_INFO', 'Информация отсутствует');
define('_MAIN_EMPTY_COMM', 'Комментарии отсутствуют');

define('_MAIN_CACHE_SIZE', 'Размер кэша');
define('_MAIN_CACHE_INFO', 'У вас на сайте активирована система кэширования базы данных. А это значит, что запросы проходящие через mysql класс системы, записываются в кэш и обновляются после определённого промежутка времени. Если Вы вносили изменения вне сайта, в структуру базы данных или отключили её вовсе, советую почистить кэш системы кнопкой ниже.');
define('_MAIN_CLEARCACHE', 'Очистить кэш');

define('_BBLOCK', 'блок');
define('_BLOCK_ADDING', 'Добавление блока');
define('_BLOCK_TITLE_TT', 'Заголовок блока отображаемый на сайте');
define('_BLOCK_FILE', 'Файл');
define('_BLOCK_FILE_WITHOUT', 'Без файла');
define('_BLOCK_DESTANATION', 'Расположение блока');
define('_BLOCK_CONTENT', 'Содержание');
define('_BLOCK_POS', 'Позиция');
define('_BLOCK_POS_TT', 'Оставьте пустым и блок попадёт в конец');
define('_BLOCK_GROUPS', 'Доступно группам');
define('_BLOCK_GROUPS_TT', 'Для выбора нескольких групп зажмите CTRL.');
define('_BLOCK_ACTIVE', 'Активный');
define('_BLOCK_ALL', 'Во всех');
define('_BLOCK_FREE', 'Свободный');
define('_BLOCK_INDEX', 'Только на главной');
define('_BLOCK_UNSHOW', 'Отрицание отмеченных');
define('_BLOCK_FILECHOOSED', '<b>Выбран файл, редактирование контента невозможно!</b> (<u>Выберите Нет Файла и редактирование будет доступно</u>)');
define('_BLOCK_FOR_TPL', 'Для шаблона');
define('_BLOCK_DELETEFROM_TYPE', 'Удалить блоки этого типа');
define('_BLOCK_TYPE_TITLE', 'Заголовок типа');
define('_BLOCK_TYPEF_TT', 'Тип для обработки в шаблонах');
define('_BLOCK_TYPE_TITLE_TT', 'Заголовок типа отображаемый в АП');
define('_BLOCK_ADD_TYPE', 'Добавить тип блока');
define('_BLOCK_STANDART', 'Настройка стандартных блоков');

define('_LOG_LOG', 'Логи системы');
define('_LOG_OK_COM', 'Действие успешно выполнено');
define('_LOG_OK_CLEAR', 'Логи ошибок успешно очищены! <a href="javascript:history.go(-1)" title="Назад">Вернуться назад</a>');
define('_LOG_NAME', 'Логи безопасности');
define('_LOG_ERROR', 'ошибок');
define('_LOG_CLEAR', 'Очистить логи');
define('_LOG_EMPTY', 'Логи пусты!');

define('_SMAILE_SMAILE', 'Смайл');
define('_SMAILE_SMAILES', 'Смайлы');
define('_SMAILE_LIST', 'Список смайлов');
define('_SMAILE_ADD', 'Добавить смайл');
define('_SMAILE_TAG', 'BB тэг');
define('_SMAILE_DESC', 'Описание');
define('_SMAILE_URL', 'URL смайла');
define('_SMAILE_DEL', 'Удалить');
define('_SMAILE_FOLDER', 'Из папки');
define('_SMAILE_TITLE', 'Управление смайлами');
define('_SMAILE_INFO_1', 'Конфигурации успешно сохранены');
define('_SMAILE_INFO_2', 'Смайл успешно добавлен');
define('_SMAILE_INFO_3', 'Смайл не добавлен, т.к. не найден на сервере.');
define('_SMAILE_FOUND', 'найден');
define('_SMAILE_NOT_FOUND', 'не найден');

define('_USER_USER', 'Пользователь');
define('_USER_USERS', 'Пользователи');
define('_USER_TITLE', 'Управление пользователями');
define('_USER_NAVIGATION', 'Навигация');
define('_USER_ADD', 'Добавление пользователя');
define('_USER_FULL_SEARCH', 'Расширенный поиск');
define('_USER_INPUT', 'Введите имя');
define('_USER_SEARCH', 'Поиск');
define('_USER_SHORT', 'Сортировать по:');
define('_USER_ABC', 'алфавиту');
define('_USER_LAST_V', 'последний визит');
define('_USER_ID', 'id');
define('_USER_SEARCH_BY', 'Искать по:');
define('_USER_NICK', 'Ник');
define('_USER_EMAIL', 'E-Mail');
define('_USER_NAME', 'Имя');
define('_USER_PASS', 'Пароль');
define('_USER_GROUP', 'Пароль');
define('_USER_SONAME', 'Фамилия');
define('_USER_IP', 'IP адрес');
define('_USER_G_D', 'Любая');
define('_USER_BANNED', 'Забанен');
define('_USER_ADD_INFO_1', 'Такой пользователь уже существует в системе');
define('_USER_ADD_INFO_2', 'Пользователь успешно добавлен!');

define('_POLL_POLLS', 'Опросы');
define('_POLL_POLL', 'Опрос');

define('_DB_DB', 'База данных');
define('_DB_TABLE', 'Таблица');
define('_DB_TABLE_NAME', 'Название таблицы');
define('_DB_TABLE_CODE', 'Кодировка');
define('_DB_TABLE_NUMB', 'Строк');
define('_DB_TABLE_SIZE', 'Размер');
define('_DB_TABLE_DEL', 'Удаление таблицы');
define('_DB_TABLE_DELETE', 'успешно удалена.');
define('_DB_TRUNCATE', 'Очистить таблицу');
define('_DB_CLEAR', 'Очищение таблицы');
define('_DB_CLEAR_OK', 'успешно очищено.');
define('_DB_DELETE', 'Удалить таблицу');
define('_DB_CHOICE', 'Выберите таблицы');
define('_DB_ABOUT', 'Описание');
define('_DB_OP_NAME', 'Оптимизация');
define('_DB_OP_DO', 'Оптимизировать');
define('_DB_OP_TEXT', 'Вы можете произвести оптимизацию базы данных, тем самым будет сэкономлено немного места на диске, а также ускорена работа базы данных. Рекомендуется использовать данную функцию минимум один раз в неделю.');
define('_DB_RE_NAME', 'Ремонт базы данных');
define('_DB_RE_DO', 'Починить');
define('_DB_RE_TEXT', 'При неожиданной остановке MySQL сервера, во время выполнения каких-либо действий, может произойти повреждение структуры таблиц, использование этой функции поможет решить вам эту проблему.');
define('_DB_BE_NAME', 'Резервное копирование');
define('_DB_BE_DO', 'Бекап');
define('_DB_BE_TEXT', 'Для сохранения в целостности данных сайта следует время от времени делать резервные копии базы данных, при потере данных вы всегда можете вернуть из бекапа сайт.');
define('_DB_BE_COPY', 'Копии на сервере');
define('_DB_BE_NO', 'Бекапов базы данных не обнаружено!');
define('_DB_BE_RES', 'Восстановить бекап');
define('_DB_BE_DEL', 'Удалить бекап');
define('_DB_BE_ERROR', 'Выполнить бекап невозможно!');
define('_DB_BE_COM', 'Резервная копия базы данных сделана и доступна в папке: ');
define('_DB_BE_BACK', 'Вернуться>>');
define('_DB_BE_SERVER', 'Информация с сервера:');
define('_DB_BE_DOWNLOAD', 'Скачать бекап.');
define('_DB_BE_REST', 'Восстановление БД');
define('_DB_BE_REST_OK', 'База данных успешно восстановлена.');
define('_DB_BE_REST_NO', 'Не удалось восстановить базу данных!');
define('_DB_BB_NAME', 'Пересчёт BB');
define('_DB_BB_DO', 'Обновить BB');
define('_DB_BB_START', 'Начало');
define('_DB_BB_END', 'Конец');

define('_COM_COM', 'Комментарии');
define('_COM_OK', 'Действие успешно выполнено');
define('_COM_LIST', 'Список комментариев');
define('_COM_LIST_M', 'Список комментариев на модерации');
define('_COM_NO', 'Комментарии отсутствуют.');
define('_COM_ID', 'ID Комментария');
define('_COM_EDIT', 'Редактирование комментария');
define('_COM_ACT', 'Активировать комментарий?');
define('_COM_TEXT', 'Текст комментария');
define('_COM_UPDATE', 'Комментарий успешно обновлён.');

define('_DOP_DOPS', 'Дополнительные поля');
define('_DOP_TEMP', 'Код для вставки в шаблон');
define('_DOP_DEL', 'Вы уверены что хотите удалить ');
define('_DOP_EMPTY', 'Дополнительные поля отсутствуют.');
define('_DOP_EDIT_DOP', 'Редактировать поле');
define('_DOP_EDIT', 'Редактировать');
define('_DOP_ADD_DOP', 'Добавить поле');
define('_DOP_ADD', 'Добавить');
define('_DOP_ADD_DEF', 'Значение по умолчанию:');
define('_DOP_ADD_TITLE', 'Название поля:');
define('_DOP_ADD_DESC', 'Описание поля:');
define('_DOP_ADD_MODULE', 'Модуль:');
define('_DOP_ADD_TYPE', 'Тип поля:');
define('_DOP_ADD_USER', 'Пользовательская часть:');
define('_DOP_TYPE_0', 'Выберите тип');
define('_DOP_TYPE_1', 'Однострочный текст');
define('_DOP_TYPE_2', 'Многострочный текст');
define('_DOP_TYPE_3', 'Выпадающий список');
define('_DOP_ERROR_1', 'Вы не заполнили заголовок поля!');
define('_DOP_ERROR_2', 'Вы не заполнили описание поля!');
define('_DOP_ERROR_3', 'Вы не выбрали тип поля!');
define('_DOP_ADDS', 'Добавление поля');
define('_DOP_EDITS', 'Редактирование поля');
define('_DOP_INFO_1', 'Дополнительное поле успешно обновлено!');
define('_DOP_INFO_2', 'Дополнительное поле успешно добавлено!');

define('_CONFIGURATION', 'Конфигурации системы');
define('_CONF_INF_TH', 'Информация к размышлению');
define('_CONF_EXPAND', 'раскрыть');
define('_CONF_SUMM', 'Всего настроек');
define('_SUCCESS_SAVE', 'Параметры успешно сохранены.');
define('_ACCEPT', 'Принять');

define('_CAT_PATH', 'Категории сайта');
define('_CAT_ADD', 'Добавление категории');
define('_CAT_ADDS', 'Категории добавлены');
define('_CAT_FAST_ADD', 'Быстрое добавление');
define('_CAT_ADDSUCCESS', 'Категория успешно добавлена. <a href="{ADMIN}/cats/add">Вернутся к добавлению</a> или <a href="{ADMIN}/cats">просмотреть список категорий</a>?');
define('_CAT_ADDFATAL', 'Категорию не удалось добавить, т.к. не все поля были заполнены вернитесь <a href="javascript:history.go(-1)" title="Назад">назад</a> и попробуйте снова!');
define('_CAT_UPDATESUCCESS', 'Категория успешно обновлена. <a href="{ADMIN}/cats">Просмотреть список категорий</a>?');
define('_CAT_NAME', 'Название категории');
define('_CAT_NAME_TT', 'Заголовок категории отображаемый на сайте');
define('_CAT_URL', 'Адрес (URI)');
define('_CAT_URL_TT', 'Имя для адреса можно по-русски, но без пробелов!!');
define('_CAT_DESCR', 'Описание категории');
define('_CAT_DESCR_TT', 'Описание категории');
define('_CAT_KEYS', 'Ключевые слова');
define('_CAT_KEYS_TT', 'Ключевые слова для мета тегов(опционально)');
define('_CAT_ICON', 'Иконка категории');
define('_CAT_ICON_NO', 'Без иконки');
define('_CAT_ICON_TT', 'Иконка категории в модуле.');
define('_CAT_INCAT', 'В категории');
define('_CAT_INCAT_TT', 'Если хотите чтобы ваша категория была под категорией.');
define('_CAT_INCAT_NO', 'Без категории');
define('_CAT_MODULE', 'Модуль категории');
define('_CAT_UPDATE', 'Обновление категории');
define('_CAT_DELETE', 'Удалить категорию - [cat]? \n\rВсе новости тоже будут удалены!');
define('_CAT_NO_CATS', 'Категорий нет, добавьте первую!');
define('_CAT_LIST', 'Список категорий');
define('_CAT_LIST_TT', 'Введите категории список. Каждая категория на новой строке');
define('_CAT_LIST_SUCCESS', 'Категория "[name]" добавлена.  <br />');
define('_CAT_ERROR_1', 'Вы не заполнили заголовок категории!');

define('_TPL_TPL', 'Шаблон');
define('_TPL_TPLS', 'Шаблоны');
define('_TPL_UPLOAD_TPL', 'Загрузить шаблон:');
define('_TPL_UPLOAD_INF', 'Выбирите файл (в формате zip) шаблона который вы хотите встроить в систему:');
define('_TPL_IN', 'Стандартный шаблон для');
define('_TPL_OUT', 'Сторонний шаблон для');
define('_TPL_LOAD', 'Скачать шаблон');
define('_TPL_DEL', 'Удалить шаблон');
define('_TPL_EDET', 'Редактировать шаблон');
define('_TPL_EDET_CSS', 'Редактировать стили');
define('_TPL_EDET_CH', 'Выбор файла tpl');
define('_TPL_EDET_CSS_CH', 'Выбор файла css');
define('_TPL_FOLD_MAIN', 'Главное');
define('_TPL_FOLD_BLOG', 'Блоги');
define('_TPL_FOLD_BOARD', 'Форум');
define('_TPL_FOLD_COMM', 'Комментарии');
define('_TPL_FOLD_CONTENT', 'Страницы');
define('_TPL_FOLD_GALLERY', 'Галерея');
define('_TPL_FOLD_GUEST', 'Гостевая');
define('_TPL_FOLD_NEWS', 'Новости');
define('_TPL_FOLD_PM', 'ПМ');
define('_TPL_FOLD_PROFILE', 'Профиль');
define('_TPL_FOLD_SEARCH', 'Поиск'); 
define('_TPL_NAME_INDEX', 'Главная страница');
define('_TPL_NAME_INFO', 'Информация');
define('_TPL_NAME_PAGE', 'Навигация');
define('_TPL_NAME_SITEMAP', 'Карта сайта');
define('_TPL_NAME_TABLE', 'Таблица контента');
define('_TPL_NAME_TITLE', 'Заголовки');
define('_TPL_NAME_WARNING', 'Предупреждения');
define('_TPL_NAME_POLL', 'Голосования');
define('_TPL_NAME_FEEDBACK', 'Обратная связь');
define('_TPL_NAME_BLOCK', 'Вывод PHP блоков');
define('_TPL_NAME_MAINPAGE', 'Контент на главной');
define('_TPL_NAME_CUSTOMS', 'Вывод новостей по шаблону');
define('_TPL_NAME_BB', 'BB коды');
define('_TPL_NAME_COM', 'Комментарий');
define('_TPL_NAME_N_CAT', 'Новость в категории');
define('_TPL_NAME_N_VIEW', 'Просмотр новости');
define('_TPL_NAME_N_MAIN', 'Новость на главной');
define('_TPL_NAME_N_ADD', 'Добавить новость');
define('_TPL_NAME_CSS_ENG', 'Стиль системы');
define('_TPL_NAME_CSS_THM', 'Стиль шаблона');
define('_TPL_INFO_0', 'Шаблон успешно удалён.');
define('_TPL_INFO_1', 'Невозможно удалить шаблон. Возможно он выбран, как основной.');
define('_TPL_INFO_2', 'Шаблон успешно выбран!');
define('_TPL_INFO_3', 'Шаблон успешно загружен на сайт!');
define('_TPL_INFO_4', 'Не удалось загрузить шаблон, проверьте правильность архива.');
define('_TPL_INFO_5', 'Шаблон успешно сохранен.');
define('_TPL_INFO_6', 'Стиль успешно сохранен.');

define('_GROUP_GROUPS', 'Группы');
define('_GROUP_NAME_SPECIAL', 'Специальная');
define('_GROUP_NAME_PROTECTED', 'Защищенная');
define('_GROUP_DEL', 'Удалить группу - ');
define('_GROUP_UPDATE', 'Обновление группы');
define('_GROUP_ADD', 'Добавление группы');
define('_GROUP_EMPTY', 'Групп нет!');
define('_GROUP_NAME', 'Название группы');
define('_GROUP_SPECIAL', 'Специальная группа');
define('_GROUP_SPECIAL_DESC', 'При выборе данного пункта, все настройки являются недействительными, группа несёт только информативный смысл');
define('_GROUP_POINTS', 'Количество очков');
define('_GROUP_POINTS_DESC', 'Если группа специальная и Вы хотите, чтобы она назначалась в зависимости от количества очков пользователя, заполните данное поле');
define('_GROUP_RIGHT_GUEST', 'Права гостя');
define('_GROUP_RIGHT_USER', 'Права пользователя');
define('_GROUP_RIGHT_MODER', 'Права модератора');
define('_GROUP_RIGHT_ADMIN', 'Права администратора');
define('_GROUP_RIGHT_BAN', 'Забанены?');
define('_GROUP_RIGHT_FULL', 'Полные права?');
define('_GROUP_RIGHT_HIDE', 'Показывать под тегом [hide]?');
define('_GROUP_ATTACH_VIEW', 'Показывать аттачи?');
define('_GROUP_ATTACH_LOAD', 'Разрешить загружать аттачи');
define('_GROUP_RIGHT_ADDNEWS', 'Разрешить добавление материалов');
define('_GROUP_RIGHT_COMMENT', 'Разрешить добавление комментариев');
define('_GROUP_VIEW_RAITING', 'Показывать рейтинг');
define('_GROUP_AVATAR_WIGHT', 'Максимальная ширина аватара');
define('_GROUP_PM', 'Максимальное количество PM:');
define('_GROUP_ICON', 'Иконка группы');
define('_GROUP_COLOR', 'Цвет групп');
define('_GROUP_INFO_0', 'Группа успешно добавлена!');
define('_GROUP_INFO_1', 'Группа успешно обновлена!');
define('_GROUP_CONFIG_NAME', 'Очки пользователя');
define('_GROUP_CONFIG_ADDNEWS', 'Добавление новости');
define('_GROUP_CONFIG_ADDNEWS_DESC', 'Сколько очков давать за добавление новости');
define('_GROUP_CONFIG_ADDCOMM', 'Добавление комментария');
define('_GROUP_CONFIG_ADDCOMM_DESC', 'Сколько очков давать за добавление комментария');
define('_GROUP_CONFIG_REG', 'Регистрация');
define('_GROUP_CONFIG_REG_DESC', 'Балл начисляется при регистрации');
define('_GROUP_CONFIG_CARMA', 'Выставление кармы');
define('_GROUP_CONFIG_CARMA_DESC', 'Если пользователю повысили карму, прибавляется данное количество баллов');
define('_GROUP_CONFIG_FRIENDS', 'Добавление в друзья');
define('_GROUP_CONFIG_FRIENDS_DESC', 'Если у пользователя появляется друг, прибавляем баллы');
define('_GROUP_CONFIG_VOTE', 'Оценка публикаций');
define('_GROUP_CONFIG_VOTE_DESC', 'Если пользователь оценил публикацию, то прибавляем баллы');

